import { describe, it, expect } from 'vitest'
import { render, screen } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import App from './App'
import { routeConfig } from './routeRegistry'
import { siteConfig } from './siteConfig'
import { methods } from '../content'
import {
  STATIC_PATHS,
  collectCanonicalPaths,
  renderSitemap,
} from '../../scripts/site-routes.mjs'

const root = process.cwd()

function renderAt(path) {
  return render(
    <MemoryRouter initialEntries={[path]}>
      <App />
    </MemoryRouter>,
  )
}

const canonical = () =>
  document.head.querySelector('link[rel="canonical"]')?.getAttribute('href')
const meta = (name) =>
  document.head.querySelector(`meta[name="${name}"]`)?.getAttribute('content')
const og = (property) =>
  document.head
    .querySelector(`meta[property="${property}"]`)
    ?.getAttribute('content')

describe('per-page metadata', () => {
  it('gives each route its own title, canonical and og:url', async () => {
    renderAt('/publications')

    expect(await screen.findByRole('heading', { level: 1 })).toBeInTheDocument()
    expect(document.title).toBe('Publications | TSR Research Group')
    expect(canonical()).toBe(`${siteConfig.url}/publications`)
    expect(og('og:url')).toBe(`${siteConfig.url}/publications`)
    expect(og('og:title')).toBe('Publications | TSR Research Group')
  })

  it('canonicalises the home page to the origin, not to a path', () => {
    renderAt('/')
    expect(canonical()).toBe(`${siteConfig.url}/`)
    expect(document.title).toBe(siteConfig.name)
  })

  it('falls back to the site description when a page gives none', () => {
    renderAt('/')
    expect(meta('description')).toBe(siteConfig.description)
  })

  it('describes a method page with its own summary', async () => {
    renderAt('/tsr')

    await screen.findByRole('heading', { level: 1, name: /Triangular Spatial/ })
    const tsr = methods.find((m) => m.slug === 'tsr')
    expect(meta('description')).toBe(tsr.summary)
    expect(canonical()).toBe(`${siteConfig.url}/tsr`)
  })

  it('does not canonicalise every page to the origin', () => {
    /*
     * The failure mode this guards against: a single hard-coded canonical in
     * index.html that never updates would tell a crawler that /people, /tsr
     * and every method page are all duplicates of the home page, and none of
     * them would be indexed.
     */
    renderAt('/people')
    expect(canonical()).not.toBe(`${siteConfig.url}/`)
    expect(canonical()).toBe(`${siteConfig.url}/people`)
  })
})

describe('the sitemap', () => {
  it('lists exactly the canonical routes the router serves', async () => {
    /*
     * The sitemap is generated by a plain Node script, because the build
     * cannot import the JSX route table. This is where the two are held
     * together: if routing changes and the script does not follow, the
     * sitemap would advertise pages that no longer exist, and this fails.
     */
    const fromScript = await collectCanonicalPaths(resolve(root, 'src/content'))

    const published = methods
      .filter((m) => m.status === 'published')
      .map((m) => m.path)
    const expected = [...STATIC_PATHS, ...published]

    expect(fromScript.slice().sort()).toEqual(expected.slice().sort())

    /* And every one of them really resolves in the route table. */
    const routed = new Set(routeConfig.map((r) => r.path))
    for (const path of fromScript) {
      expect(routed.has(path), `${path} is in the sitemap but not routed`).toBe(
        true,
      )
    }
  })

  it('excludes drafts', async () => {
    const draft = methods.find((m) => m.slug === 'key-to-image')
    expect(draft.status).toBe('draft')

    const paths = await collectCanonicalPaths(resolve(root, 'src/content'))
    expect(paths.some((p) => p.includes('key-to-image'))).toBe(false)
  })

  it('excludes legacy aliases and retired addresses', async () => {
    const paths = await collectCanonicalPaths(resolve(root, 'src/content'))

    /* Aliases redirect: listing them would offer two URLs for one page. */
    for (const alias of ['/mirror-image', '/commonkeys', '/source-code']) {
      expect(paths, alias).not.toContain(alias)
    }
    /* Retired addresses 404 on purpose. */
    for (const gone of ['/problems', '/community']) {
      expect(paths, gone).not.toContain(gone)
    }
  })

  it('renders valid XML with absolute URLs', () => {
    const xml = renderSitemap(['/', '/people'], siteConfig.url)

    expect(xml).toContain('<?xml version="1.0" encoding="UTF-8"?>')
    expect(xml).toContain('http://www.sitemaps.org/schemas/sitemap/0.9')
    expect(xml).toContain(`<loc>${siteConfig.url}/people</loc>`)
    expect(xml).not.toMatch(/<loc>\/[^<]*<\/loc>/)
  })
})

describe('robots.txt', () => {
  it('allows crawling and points at the sitemap', () => {
    const robots = readFileSync(resolve(root, 'public/robots.txt'), 'utf8')

    expect(robots).toMatch(/^User-agent: \*$/m)
    expect(robots).toMatch(/^Allow: \/$/m)
    expect(robots).toContain(`Sitemap: ${siteConfig.url}/sitemap.xml`)
  })
})

describe('the static head', () => {
  const html = readFileSync(resolve(root, 'index.html'), 'utf8')

  it('ships a description and Open Graph defaults for crawlers without JS', () => {
    expect(html).toContain('name="description"')
    expect(html).toContain('property="og:title"')
    expect(html).toContain('property="og:description"')
    expect(html).toContain('property="og:url"')
    expect(html).toContain('rel="canonical"')
  })

  it('claims no social image while none has been approved', () => {
    /*
     * A cropped logo would look like a finished card and quietly become the
     * permanent one. Text-only previews until there is a real asset.
     */
    expect(html).not.toContain('og:image')
    expect(html).toContain('name="twitter:card" content="summary"')
  })

  it('points at the site favicon rather than a starter asset', () => {
    expect(html).toContain('href="/favicon.svg"')
    const favicon = readFileSync(resolve(root, 'public/favicon.svg'), 'utf8')
    /* The Vite starter mark was purple; ours is the group's triangle. */
    expect(favicon).not.toContain('863bff')
    expect(favicon).toContain('TSR Research Group')
  })
})

describe('public wording matches what the repositories actually are', () => {
  it('makes no collective open-source claim while licences are missing', () => {
    /*
     * Five of the six repositories the group owns have no LICENSE file, which
     * means they are not open source however public they are — see
     * CONTENT-REVIEW item 29. The site says "public" and "research software"
     * instead. This fails if the claim comes back before the licences do.
     */
    for (const file of [
      'src/content/site.json',
      'src/content/home.json',
      'src/content/pages.json',
      'index.html',
    ]) {
      const text = readFileSync(resolve(root, file), 'utf8').toLowerCase()
      expect(text, file).not.toContain('open-source')
      expect(text, file).not.toContain('open source')
    }
  })
})
